nick = input('Qual seu nick meu fi?')
print('Olá {},sejas muito bem vindo meu fi.'.format(nick))
jogo = input('Qual seu jogo favorito?')
patente = input('Qual sua patente ou level?')
hora = input('Em qual horário você joga?')
print('Interessante {}. Fico muito feliz que jogue Counter Strike.'.format(nick))
amigos = input('Você tem amigos no cs?')
quantidade = input('Quantos são?')
nicks = input('Quais os nicks deles?')
jogam = input('Uau legal isso! Seus amigos,sempre jogam com você?')
print('Muito legal saber disso, {}. Fico feliz por seus amigos, {} jogarem com você!'.format(nick, nicks))
