n = int(input('Digite um numero para saber sua tabuada:'))
print('-'*12)
print('{}x1= {:2}'.format(n, n*1))
print('{}x2= {:2}'.format(n, n*2))
print('{}x3= {:2}'.format(n, n*3))
print('{}x4= {:2}'.format(n, n*4))
print('{}x5= {:2}'.format(n, n*5))
print('{}x6= {:2}'.format(n, n*6))
print('{}x7= {:2}'.format(n, n*7))
print('{}x8= {:2}'.format(n, n*8))
print('{}x9= {:2}'.format(n, n*9))
print('{}x10= {:2}'.format(n, n*10))
print('-'*12)