d = input('Digite algo:')
print(d.isalnum())
print(d.isalpha())
print(d.isascii())
print(d.isdigit())
print(d.islower())
print(d.isdecimal())
print(d.isidentifier())
print(d.isnumeric())
print(d.isprintable())
print(d.isspace())
print(d.istitle())
print(d.isupper())
print('O tipo primitivo desse valor é',type(d))
